### ISSUE TITLE
大哥，微信企业不见推送啊

### ISSUE THREAD

**Issue by wmgm183** [guanguans/yii-log-target#9]
是我方式不对吗？

控制器
```
    public function actionTest(){
        Yii::error('1111');
    }
```

**Comment by guanguans** [comment]
@wmgm183 错误日志和配置可以贴一下吗

**Comment by wmgm183** [comment]
没有报错，就是安装说明 $ composer require guanguans/yii-log-target --prefer-dist -vvv
安装。然后在log那配置了下       
 // // 企业微信群机器人
        // [
        //     'class'   => \Guanguans\YiiLogTarget\WeWorkTarget::class,
        //     'levels'  => ['error'],
        //     // 'debug'   => true,
        //     'token'   => '3d5a3-ceff-4da8-bcf3-ff5891778fb7',
        // ],
![1](https://user-images.githubusercontent.com/62553011/174537423-e7f68520-eee2-434b-9958-2215e71ef428.png)
![2](https://user-images.githubusercontent.com/62553011/174537428-0ecdc0b8-aee4-460e-87a4-a04890040000.png)

**Comment by guanguans** [comment]
![image](https://user-images.githubusercontent.com/22309277/174538209-4eab6d9f-0593-40fa-b4c5-5d70eea60a3e.png)

这个 debug 配置开启一下。执行 `Yii::info('1111);` 然后查看对应应用的的日志报错。

**Comment by wmgm183** [comment]
> ![图片](https://user-images.githubusercontent.com/22309277/174538209-4eab6d9f-0593-40fa-b4c5-5d70eea60a3e.png)
> 
> 这个调试配置开启一下。然后执行`Yii::info('1111);`查看应用的日志报错。

    'errcode' => 93000
    'errmsg' => 'invalid webhook url, hint: [1655706696626614187726246], from ip: 0.0.0.0, more info at https://open.work.weixin.qq.com/devtool/query?e=93000'
感谢大佬 百忙之中的回复 是token错了吗，   不是新建 一个应用然后获取 吗

`https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=企业id&corpsecret=应用`id。
post 这个接口 返回的token吗

**Comment by guanguans** [comment]
是企业微信群机器人通知，具体可以查看 [这部分文档](https://developer.work.weixin.qq.com/document/path/91770)、[guanguans/notify](https://github.com/guanguans/notify)。

**Comment by wmgm183** [comment]
> 是企业微信群机器人通知，具体可以查看 [这部分文档](https://developer.work.weixin.qq.com/document/path/91770)、[guanguans/notify](https://github.com/guanguans/notify)。

谢谢大佬。
